### ISSUE TITLE
AttributeError: 'module' object has no attribute 'install'

### ISSUE THREAD

**Issue by con-f-use** [xolox/python-coloredlogs#10]
The following example from the documentation:

    import coloredlogs, logging
    coloredlogs.install()
    logger = logging.getLogger()
    logger.info("this is an informational message")

Gives this error in python 2.7.6 on Ubuntu 14.04:

    Traceback (most recent call last):
      File "./coloredlogs.py", line 21, in <module>
        import coloredlogs, logging
      File "/home/confus/misc/test/coloredlogs.py", line 22, in <module>
        coloredlogs.install()
    AttributeError: 'module' object has no attribute 'install'

**Comment by xolox** [comment]
Your traceback indicates that you created a file called `coloredlogs.py` to test the coloredlogs package and module. Python defaults to importing from the current working directory in preference to the regular module search path and so your `coloredlogs.py` script is importing itself. Rename the script you created and everything will be fine.

**Comment by xolox** [comment]
For posterity: I've made this mistake myself now and then which is why I recognize it so easily now ;-)

**Comment by con-f-use** [comment]
Yes, that was the first thing I thought, too. I even deleted the `coloredlogs.py` and the error persisted. Turns out, I left the compiled version `coloredlogs.pyc` in the directory. How stupid of me, sorry for bothering you.

**Comment by xolox** [comment]
Been there, done that, got the t-shirt! It happens to the best of us :-).
