### ISSUE TITLE
Autocall coloredlogs.install based on an environment variable

### ISSUE THREAD

**Issue by anntzer** [xolox/python-coloredlogs#19]
It is possible to detect whether an environment variable (say, `COLOREDLOGS_AUTOUSE`) is set whenever Python starts, and, if it is, automatically import coloredlogs and install it.
See https://github.com/ionelmc/python-hunter/blob/master/setup.py and http://python-hunter.readthedocs.io/en/latest/introduction.html#via-environment-variable for an example.
Basically the idea would be to provide a `coloredlogs.pth` file in .../site-packages/ with the contents (approximately)

```
import os; __import__("coloredlogs").install() if os.environ.get("COLOREDLOGS_AUTOUSE") else None
```

and rely on the fact that Python will execute any line starting with `import` in a pth file in the site-packages directory.

The advantage would be to make the use of coloredlogs completely transparent for the author of the code, and directly switchable by the end user.

**Comment by xolox** [comment]
Hi Antony and thanks for the feature request here and implementation in pull request #20. I've merged your changes and released coloredlogs version 5.2 which includes the suggested .pth file, so I'm going to close this issue now.
