### ISSUE TITLE
deadlock between import and coloredlogs on Python 2.7

### ISSUE THREAD

**Issue by davidfraser** [xolox/python-coloredlogs#29]
I have a scenario where our application is hanging on startup.
We start some background threads early on to monitor background processes. These log messages received from those processes.
We then import some configurable modules that can take some time to import. And some of them log messages on import (instantiating singleton objects).

Unfortunately, this means they are holding the import lock. But on Python 2.7, copy.copy runs an import of `copyreg` every single time it is called. And coloredlogs calls `copy.copy` when formatting a log. So it then blocks waiting for the import lock, and when the main thread tries to log, it tries to grab the logging lock that is being held in the background thread, deadlocking.

I have a [gist that demonstrates this](https://gist.github.com/davidfraser/a560be999adc235231eb8c60d7e5a0f5) as a small commandline program.

**Comment by davidfraser** [comment]
What goes wrong - some more details

Code running in the startup thread:

1. starts background threads that monitor subprocesses
2. continues to import other modules after it has started background threads
3. those imports take a long time to import and have side-effects like instantiating singletons, and they hold the global **import lock** while they are running

Code running in a background thread:

4. logs something which gets processed with a `coloredlogs` handler
5. This logging call obtains the **logging lock** to emit records
6. the `coloredlogs` module uses `copy.copy` to make an adjusted copy of the log record, so that it can change its message
7. the `copy.copy` method tries to import the ​`copyreg` module, to look for registered copy methods, every time it is called
8. this `copyreg` import tries to obtain the **import lock**, while it is holding the **logging lock**, and so blocks waiting for the main thread

Code running in the startup thread (which is still holding the global **import lock**):

9. The code run as part of the import process logs messages
10. These `logging` calls try to acquire the **logging lock** to emit records, and deadlock waiting for the background thread which is waiting for this thread

On Python 2.7.13, the sequence of calls in the background thread is as follows:

* ​[copy.copy](https://github.com/python/cpython/blob/2.7/Lib/copy.py#L66) method gets the `__reduce_ex__` attribute of the `LogRecord` object
* This is the default [​object_reduce_ex function](https://github.com/python/cpython/blob/2.7/Objects/typeobject.c#L3473), which calls `_common_reduce` in the same file
* This calls ​[import_copyreg](https://github.com/python/cpython/blob/2.7/Objects/typeobject.c#L3219), which unconditionally tries to import `copyreg` (using `PyImport_Import`, which obtains the lock)

This would not happen on Python 3.3+, since Python 3 has a per-module import lock, not a global one (and there are patches that mean that it also caches the `copyreg` module handle it has)

**Comment by xolox** [comment]
Hi David, thanks for the detailed feedback and for getting to the bottom of this obscure issue! I must say I'd never imagined that a `copy.copy()` call might be the cause of deadlocks between threads.

Based on [your gist](https://gist.github.com/davidfraser/a560be999adc235231eb8c60d7e5a0f5) I was able to reliably reproduce the issue and if my testing is correct I've now resolved the issue: I just released coloredlogs 6.3 which implements the minimal subset of `copy.copy()` that's needed to copy `logging.LogRecord` objects (a very limited use case) without using the `copy` module.

If coloredlogs 6.3 doesn't resolve the problem for you then feel free to reopen this issue.

**Comment by davidfraser** [comment]
Thanks for this speedy and brilliant resolution; it works perfectly
