### ISSUE TITLE
coloredlog's streamhandler should re-fetch sys.stderr every time

### ISSUE THREAD

**Issue by anntzer** [xolox/python-coloredlogs#30]
logging's "lastResortHandler" (the default handler) refetches the stderr attribute of the sys module every time just before writing to it (https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L1077), thus allowing patching of sys.stderr (e.g., via contextlib.redirect_stderr).  It would be nice if coloredlog's handler did the same (likewise to support patching of sys.stderr).

A possible API would be to default the "stream" kwarg to coloredlogs.install to None (instead of the current sys.stderr), which would have the meaning "sys.stderr, but refetched before each write".

**Comment by xolox** [comment]
Thanks for the feedback Antony, I just merged #31!
