### ISSUE TITLE
Support for 256-color output

### ISSUE THREAD

**Issue by anntzer** [xolox/python-coloredlogs#35]
It would be appreciated if it was possible to use 256-color output (https://en.wikipedia.org/wiki/ANSI_escape_code#Colors), e.g. by allowing the "color" field of DEFAULT_{FIELD,LEVEL}_STYLES to be a 0-255 integer.

**Comment by mattconsto** [comment]
To add onto this, it would be useful to be able to change the background colour as well as the foreground colour. Right now it's hard to distinguish critical logs from error logs.

**Comment by xolox** [comment]
Thanks for the feedback Antony and Matthew. Release 9.0 of coloredlogs adds support for 256 color mode and background colors. As suggested by Antony the `color` field (as well as the `background` field) now support integer values which select colors from the 256 color mode palette.
