### ISSUE TITLE
v7.3: Windows build requirements error (with fix)

### ISSUE THREAD

**Issue by btxgit** [xolox/python-coloredlogs#43]
I just ran into this while installing via setup.py install on a windows system w/Python 2.7.13:

<cut out irrelevant output>
Processing dependencies for coloredlogs==7.3
Searching for r
Reading https://pypi.python.org/simple/r/
No local packages or working download links found for r
error: Could not find suitable distribution for Requirement.parse('r')

The problem:
setup.py, function: get_install_requires()

You check for win32 to determine if you need to add colorama as a dependency.  The problem is you use install_requires.extend with 'colorama' as the arg.  extend, however, expects an iterable, so it turns "colorama" into ["c", "o", "l", "o", "r", "a", "m", "a"]. 

The fix:

File: setup.py

**Change:** 
`            install_requires.extend('colorama')`
to **either:**
`            install_requires.append('colorama')`
**or**:
`            install_requires.extend(['colorama'])`

**Comment by xolox** [comment]
Thanks for the clear bug report @btxgit, this has been fixed in version 7.3.1.
