### ISSUE TITLE
publish release notes

### ISSUE THREAD

**Issue by jab** [xolox/python-coloredlogs#55]
I just noticed you've released several versions of this library since the version I first installed (7.3), but I have no idea what's changed since then. I checked the README, https://coloredlogs.readthedocs.io, https://github.com/xolox/python-coloredlogs/releases, and for some CHANGELOG file, and don't see this information tracked anywhere. Could you please provide a summary of notable changes in releases? Thanks for this project.

**Comment by xolox** [comment]
Hi @jab and thanks for the feedback. A changelog is now available on [GitHub](https://github.com/xolox/python-coloredlogs/blob/master/CHANGELOG.rst) and [Read the Docs](https://coloredlogs.readthedocs.io/en/latest/changelog.html). I hope this helps!

**Comment by jab** [comment]
Awesome, thanks @xolox!
