### ISSUE TITLE
error in logger

### ISSUE THREAD

**Issue by rakshaverma** [xolox/python-coloredlogs#56]
[book_a.txt](https://github.com/xolox/python-coloredlogs/files/1935355/book_a.txt)
[main.txt](https://github.com/xolox/python-coloredlogs/files/1935356/main.txt)
[search.txt](https://github.com/xolox/python-coloredlogs/files/1935357/search.txt)
 this is my code and the error is logger is not defined please suggest me

**Comment by xolox** [comment]
This is not related to coloredlogs in any way, so I'm going to close this issue.
