### ISSUE TITLE
Error when user provides a customized record_factory function for 10.0 version

### ISSUE THREAD

**Issue by WeijieH** [xolox/python-coloredlogs#59]
Following the logging document https://docs.python.org/3/library/logging.html
Do:

```
old_factory = logging.getLogRecordFactory()

def record_factory(*args, **kwargs):
    record = old_factory(*args, **kwargs)
    record.custom_attribute = 0xdecafbad
    return record

logging.setLogRecordFactory(record_factory)
```

Then coloredlogs 10.0 throws error:

```
File "C:\anaconda3\envs\pt4\lib\site-packages\coloredlogs\__init__.py", line 1110, in format
    else logging.LogRecord
TypeError: __class__ must be set to a class, not 'function' object
```

**Comment by xolox** [comment]
Hey Weijie and thanks for the feedback! I've just released [coloredlogs 11.1](https://coloredlogs.readthedocs.io/en/latest/changelog.html#release-11-1-2020-02-15) which should resolve the problem you reported. I also added a test to avoid regressions in the future.
