### ISSUE TITLE
Filter instead of logger

### ISSUE THREAD

**Issue by hamiltont** [xolox/python-coloredlogs#6]
IIRC, a LogFilter can actually modify the LogRecord objects. Perhaps instead of (inflexibly) hard-coding the log format, you could just define a custom filter that wraps parts of the LogRecord with the proper unicode color codes?

**Comment by xolox** [comment]
Hi @Hamilton and thanks for the feedback. Please try out version 3.0 (just released). I've changed the `ColoredStreamHandler` into a `ColoredFormatter` that supports user defined format strings just like `logging.Formatter` does. I did end up using a filter, but not to inject ANSI escape sequences (that's better done from a custom formatter), but instead to give log records a `hostname` attribute (this was one thing holding me back from using a formatter - the logging module doesn't natively expose hostnames).

**Comment by hamilton** [comment]
Wrong Hamilton. But I got your back, @hamiltont

**Comment by xolox** [comment]
@hamilton: Sorry about the bogus notification and thanks for relaying it :-).

**Comment by hamiltont** [comment]
Nice! THis looks like a much better approach, I'll check it out when there's time

@hamilton thanks man, I'll get you next time thru when someone tags me instead ;-)
