### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by eabouhaydar** [xolox/python-coloredlogs#64]
Hello, 
When I try to run my python program I got an error like this:
AttributeError: 'str' object has no attribute 'items'
This error comes from <path_to_my_virtualenv>/lib/python3.5/site-packages/coloredlogs/__init__.py:994: 
    `self.level_styles = self.nn.normalize_keys(DEFAULT_LEVEL_STYLES if level_styles is None else level_styles)`

This is caused by the mismatch of the constructor of coloredlogs and the constructor of logging.Formatter. 
This issue can be bypassed by explicitly specify each parameters of the coloredlogs constructor. Another alternative could be put the style parameter in fourth position.

**Comment by xolox** [comment]
Hi Elie and thanks for the feedback. I've just released [coloredlogs 12.0](https://coloredlogs.readthedocs.io/en/latest/changelog.html#release-12-0-2020-02-16) which changes the order of positional arguments to be compatible with the Python standard library.
