### ISSUE TITLE
Proposal to change argument order in constructor to be consistent with stdlib

### ISSUE THREAD

**Issue by FlorianLudwig** [xolox/python-coloredlogs#75]
Current constructor:
```python
def __init__(self, fmt=None, datefmt=None, level_styles=None, field_styles=None, style=DEFAULT_FORMAT_STYLE):
```

The [python standard lib expects the first three parameters](https://github.com/python/cpython/blob/3.7/Lib/logging/config.py#L673) to be `fmt, datefmt, style`.

 To make coloredlogs usable with the config system in the stdlib I like to propose to move the `style`.

**Comment by xolox** [comment]
Hi Florian and thanks for the feedback. I've just released [coloredlogs 12.0](https://coloredlogs.readthedocs.io/en/latest/changelog.html#release-12-0-2020-02-16) which changes the order of positional arguments to be compatible with the Python standard library.
