### ISSUE TITLE
Feature Request : username (analog to programname)

### ISSUE THREAD

**Issue by bitranox** [xolox/python-coloredlogs#76]
it would be super if You can implement 
username (analog to programname) and include it into the fieldstyles.

what You think ?

yours sincerely

Robert

**Comment by xolox** [comment]
Hi Robert and thanks for the suggestion. I've just released [coloredlogs 11.3](https://coloredlogs.readthedocs.io/en/latest/changelog.html#release-11-3-2020-02-15) which adds support for the `%(username)s` field. Just add the new field to your custom format string and everything should magically work :innocent: (once you've upgraded to the new version).

**Comment by bitranox** [comment]
Dear Xolox, 
thank You so much, thats useful.
But can You also please add %(pid)s analog to username, programname ? 
The reason is, if You run more then one instance of Your program (or forks of subprograms) You can not be clear which child/instance is logging to the logfile. (If You have a logging system that can handle logging from more then one process)
You might see the PID it in the linux syslog (if it is used), but not in the logfile.
At the moment I do this programmatically, by formatting the format string when adding my (special) stream handler, but it can make sense to support also the %(pid)s

and I totally agree to dump python 3.4 ;-)

yours sincerely,
and thanks for the new release !

Robert

**Comment by bitranox** [comment]
Uh, oh, forget it - of course there is  %(process)d

but can there be  %(hostname_short)s  because in my logs it always logs the fqdn like : 

```
[root@lxc-pydev.local.rotek.at][INFO] some logging event
```

and I would like to have like

```
[root@lxc-pydev][INFO] some logging event
```

yours sincerely
Robert
