### ISSUE TITLE
levelname format not showing

### ISSUE THREAD

**Issue by Puyodead1** [xolox/python-coloredlogs#77]
Hello, 
I'm trying to format the output and put the levelname in square brackets, everything else formats correctly except the levelname which doesn't show.
![image](https://user-images.githubusercontent.com/14828766/69001428-fcaf5400-08ab-11ea-8681-a6486c496bff.png)
Here is the code I'm using:
```
verboselogs.install()
logger = logging.getLogger("PyBot")
coloredlogs.install(level="INFO", logger=logger, fmt="[%(levelname)s] %(asctime)s: %(message)s", datefmt="[%m-%d-%Y %I:%M:%S]")
```

**Comment by Puyodead1** [comment]
Found out that the level names are black so they're hidden in Command Prompt

**Comment by CodingKoopa** [comment]
Quick fix, for anyone else wondering:

```py
coloredlogs.DEFAULT_FIELD_STYLES["levelname"]["color"] = "white"
```
