### ISSUE TITLE
the ansi2html scripts collides with the ansi2html package

### ISSUE THREAD

**Issue by jlec** [xolox/python-coloredlogs#8]
What is the purpose of this package installing the script under ansi2html instead of coloredlogs or so?

**Comment by xolox** [comment]
Hi Justin and thanks for the feedback!

When I originally picked the `ansi2html` name I clearly didn't put much thought into name collisions, sorry about that. As you suggested I've now changed the name of the command line program to `coloredlogs`, with the ANSI to HTML conversion exposed as `coloredlogs --to-html`.

I hope/assume this resolves your issue and obviates the need to patch the `setup.py` script.

**Comment by jlec** [comment]
Thanks a bunch! Looks good. I will bump the version for Gentoo today.
