### ISSUE TITLE
Honor NO_COLOR environment variable

### ISSUE THREAD

**Issue by PhilippWendler** [xolox/python-coloredlogs#88]
A quasi standard has been established that programs should not color their output if the `NO_COLOR` environment variable is set (cf. https://no-color.org/) and many programs and logging libraries already support that. So I suggest for coloredlogs to adopt this as well, i.e., silently avoid coloring the output just like it does if it detects that the output does not go to a console.

Of course, as a developer using coloredlogs I could skip importing coloredlogs by myself if the environment variable is set, but I guess it would be nice for users if the library would implement this itself, such that all projects using it would benefit from it.

**Comment by xolox** [comment]
Hi Philipp and thanks for the suggestion. I've just published coloredlogs [release 14.2](https://coloredlogs.readthedocs.io/en/latest/changelog.html#release-14-2-2020-12-10) which adds support for `$NO_COLOR`.
