### ISSUE TITLE
Jenkins Output Issue

### ISSUE THREAD

**Issue by Binternet** [xolox/python-coloredlogs#90]
coloredlogs works fine on my terminal:

![Screen Shot 2020-04-30 at 15 08 18](https://user-images.githubusercontent.com/438361/80715449-0c8bbf00-8aff-11ea-9133-c9fa67415e77.png)

Yet on Jenkins console, no color is shown:

![Screen Shot 2020-04-30 at 15 07 51](https://user-images.githubusercontent.com/438361/80715479-144b6380-8aff-11ea-8a97-7ef2199bf661.png)

After downgrading from `coloredlogs==14.0` to `coloredlogs==12.0` it was fixed:
![Screen Shot 2020-04-30 at 16 15 49](https://user-images.githubusercontent.com/438361/80715522-21685280-8aff-11ea-9890-f571bee72562.png)

**Comment by bitranox** [comment]
Since peter seems to be absent atm, You might try that one : 
https://github.com/bitranox/bitranox_coloredlogs

**Comment by Jordi-Pineiro** [comment]
`coloredlogs.install(isatty=True)`
Found here:
https://dustinoprea.com/2017/06/06/colored-logging-in-python-under-jenkins/
