### ISSUE TITLE
coloredlogs and humanfiendly on travis ... 

### ISSUE THREAD

**Issue by bitranox** [xolox/python-coloredlogs#94]
Dear Peter,
as You might know, colored logs on travis is not easy - since they use a filter program as soon as You have a secret in the travis.yml to avoid exposing passwords.

without a secret, everything is working fine.

it seems that coloredlogs is adding the normal StreamHandler even if I put isatty=True.

I forked, and also sent You a PR - please check it.

If You made an ovverride like `isatty=True` it is not good to check again if the terminal is reporting that it can use colors - we override for a reason !

isatty can have three values : 

```
isatty=None  ---> use color if possible (through detection)
isatty = False ---> do not use color
isatty = True --> force color (now it behaves exactly like "None" )
```

check the binder : https://mybinder.org/v2/gh/bitranox/bitranox_coloredlogs/master?filepath=bitranox_coloredlogs.ipynb

Yours sincerely 

Robert

**Comment by xolox** [comment]
Hi and thanks for the feedback. You're right that the override should disable the check, it was a bug that it didn't. I've just published coloredlogs [release 14.1](https://coloredlogs.readthedocs.io/en/latest/changelog.html#release-14-1-2020-12-10) which fixes this issue.
